"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "styled-components";
import { theme } from "~/styles/defaultTheme";
import { GlobalStyle } from "~/styles/global";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raul Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
